### ISSUE TITLE
Matplotlib deprecation warnings

### ISSUE THREAD

**Issue by christopherlovell** [1313e/CMasher#53] opened 2023-08-31 13:09 UTC
On matplotlib 3.7 I am getting the following errors when importing and using cmasher

    MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. 
    Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
    cmap = mplcm.get_cmap(cmap)

And the following:

    MatplotlibDeprecationWarning: The register_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. 
    Use ``matplotlib.colormaps.register(name)`` instead.
    mplcm.register_cmap(cmap=cmap_mpl_r)

These methods should be updated as described.

**Comment by neutrinoceros** [comment] 2023-10-04 12:30
This looks like a dup' of #43
FYI the problem is already addressed on the dev branch, what's missing is a release.

**Comment by neutrinoceros** [comment] 2023-12-17 07:13
Also see #79 and #74 .
I'm preparing a new release for which this problem is the main motivation.

**Comment by neutrinoceros** [comment] 2023-12-18 07:46
This is now resolved with the release of CMasher 1.7
see https://github.com/1313e/CMasher/releases/tag/v1.7.0

**Closed by neutrinoceros** 2023-12-18 07:46 UTC
Labels: feature request
